name: Echo GitHub Actions comments

on:
  issues:
    types: [closed]

jobs:
  echo_comments:
    runs-on: ubuntu-latest

    steps:
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.issue.number }}
          body-includes: hello
          direction: last
