name: Echo GitHub Actions comments

on:
  issues:
    types: [opened, reopened]

jobs:
  echo_comments:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Get issue comments
      id: issue_comments
      run: |
        comments=$(curl -s https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments?access_token=${{ secrets.GITHUB_TOKEN }})
        echo ::set-output name=comments::$comments

    - name: Echo GitHub Actions comments
      run: |
        echo "Searching for GitHub Actions comments..."
        comments=$(echo "${{ steps.issue_comments.outputs.comments }}" | jq '.[] | select(.user.login == "github-actions[bot]") | .body')
        echo "$comments"
