name: Print message on issue creation

on:
  issues:
    types: [opened]

jobs:
  print_message:
    runs-on: ubuntu-latest

    steps:
    - name: Print message
      run: |
        echo "hello world"
