name: Add comment to issue

on:
  issues:
    types: [opened, reopened]

jobs:
  add_comment:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Add comment
        uses: peter-evans/create-or-update-comment
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello World