name: Add comment to issue

on:
  issues:
    types: [opened, reopened]

jobs:
  add_comment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure Git
      run: |
        git config --global user.email "github-actions@example.com"
        git config --global user.name "GitHub Actions"

    - name: Add comment to issue
      uses: peter-evans/create-or-update-comment@v2
      with:
        issue-number: ${{ github.event.issue.number }}
        body: |
          hello world
